name: Run Automation Tests

on:
  repository_dispatch:
    types: [run-automation-tests]

jobs:
  automation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Automation Test Repo
        uses: actions/checkout@v3

      - name: Set up Python + Pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies (if needed)
        run: |
          pip install -r requirements.txt || true

      - name: Run Automation Tests
        run: |
          pytest
